language: node_js
node_js:
  - '11.10.1'
env:
  global:
    - CC_TEST_REPORTER_ID=8df2e3631705d21b07ba8a13f8347a5c1d807b8a38ee3f261c2d97b34aaaa2c4
  matrix:
    - REACT=16.7

install:
  - npm install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: npm test

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
