export const SIGN_UP_USER_REQUEST = 'SIGN_UP_USER_REQUEST';
export const SIGN_UP_USER_SUCCESS = 'SIGN_UP_USER_SUCCESS';
export const SIGN_UP_USER_FAILURE = 'SIGN_UP_USER_FAILURE';
export const SIGN_IN_USER_REQUEST = 'SIGN_IN_USER_REQUEST';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_FAILURE = 'SIGN_UP_USER_FAILURE';
export const SIGN_OUT_USER = 'SIGN_OUT_USER';
export const AUTHENTICATION_REQUEST = 'AUTHENTICATION_REQUEST';
export const AUTHENTICATION_FAILURE = 'AUTHENTICATION_FAILURE';
export const AUTHENTICATION_SUCCESS = 'AUTHENTICATION_SUCCESS';

export const FETCH_ALL_USER_PARCELS_REQUEST = 'FETCH_ALL_USER_PARCELS_REQUEST';
export const FETCH_ALL_USER_PARCELS_SUCCESS = 'FETCH_ALL_USER_PARCELS_SUCCESS';
export const FETCH_ALL_USER_PARCELS_FAILURE = 'FETCH_ALL_USER_PARCELS_FAILURE';
export const UPDATE_USER_PARCEL_REQUEST = 'UPDATE_USER_PARCEL_REQUEST';
export const UPDATE_USER_PARCEL_SUCCESS = 'UPDATE_USER_PARCEL_SUCCESS';
export const UPDATE_USER_PARCEL_FAILURE = 'UPDATE_USER_PARCEL_FAILURE';

export const CHANGE_PARCEL_DESTINATION_REQUEST = 'CHANGE_PARCEL_DESTINATION_REQUEST';
export const CHANGE_PARCEL_DESTINATION_FAILURE = 'CHANGE_PARCEL_DESTINATION_FAILURE';
export const CHANGE_PARCEL_DESTINATION_CONFIRM_NEWPRICE = 'CHANGE_PARCEL_DESTINATION_CONFIRM_NEWPRICE';
export const CHANGE_PARCEL_DESTINATION_SUCCESS = 'CHANGE_PARCEL_DESTINATION_SUCCESS';

export const CREATE_AN_ORDER_REQUEST = 'CREATE_AN_ORDER_INITIAL_REQUEST';
export const CREATE_AN_ORDER_CONFIRMATION_FAILURE = 'CREATE_AN_ORDER_CONFIRMATION_FAILURE';
export const CREATE_AN_ORDER_CONFIRMATION_SUCCESS = 'CREATE_AN_ORDER_CONFIRMATION_SUCCESS';

export const CREATE_AN_ORDER_FAILURE = 'CREATE_AN_ORDER_FAILURE';
export const CREATE_AN_ORDER_SUCCESS = 'CREATE_AN_ORDER_SUCCESS';
export const CANCEL_DELIVERY_REQUEST = 'CANCEL_DELIVERY_REQUEST';
export const CANCEL_DELIVERY_SUCCESS = 'CANCEL_DELIVERY_SUCCESS';

export const FETCH_ALL_PARCELS_REQUEST = 'FETCH_ALL_PARCELS_REQUEST';
export const FETCH_ALL_PARCELS_SUCCESS = 'FETCH_ALL_PARCELS_SUCCESS';
export const FETCH_ALL_PARCELS_FAILURE = 'FETCH_ALL_PARCELS_FAILURE';

export const ADMIN_UPDATE_PARCEL_REQUEST = 'ADMIN_UPDATE_PARCEL_REQUEST';
export const ADMIN_UPDATE_PARCEL_FAILURE = 'ADMIN_UPDATE_PARCEL_FAILURE';
export const ADMIN_UPDATE_PARCEL_SUCCESS = 'ADMIN_UPDATE_PARCEL_SUCCESS';

export const UPDATE_PHONE_NO_FAILURE = 'UPDATE_PHONE_NO_FAILURE';
export const UPDATE_PHONE_NO_SUCCESS = 'UPDATE_PHONE_NO_SUCCESS';
